stages:
  step_1:
    cmd: python -m scripts.action_a --input data/raw.txt --output output/step_1.txt
    deps:
    - data/raw.txt
    - scripts/action_a.py
    outs:
    - output/step_1.txt
  step_2:
    cmd: python -m scripts.action_b --input output/step_1.txt --output output/step_2.txt
    deps:
    - output/step_1.txt
    - scripts/action_b.py
    outs:
    - output/step_2.txt
  step_3:
    cmd: python -m scripts.action_c --input output/step_2.txt --output output/step_3.txt
    deps:
    - output/step_2.txt
    - scripts/action_c.py
    outs:
    - output/step_3.txt
